name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
    
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: williambpaiva
        password: ${{ secrets.PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: williambpaiva/go_ci:${{ github.ref_name }}
