name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install Flask
    - uses: AppThreat/sast-scan-action@master
      with:
        type: "python"
  
  build:
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: programa
        path: main

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  alert:
    runs-on: windows-latest
    steps:
      - name: Send Telegram Alert
        env:
          TELEGRAM_TOKEN: '7082971552:AAGbOG6amP--nccNR9Oxpr4cdJylx-3f2zU'
          TELEGRAM_CHAT_ID: '-4245329360'
        shell: pwsh
        run: |
          $url = "https://api.telegram.org/bot${env:TELEGRAM_TOKEN}/sendMessage"
          $body = @{
            chat_id = "${env:TELEGRAM_CHAT_ID}"
            text = " --------NOTIFICACAO ENVIADA---------"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $url -Method Post -Body $body -ContentType "application/json"
