name: CI
on:
  push:
    branches:
      - main

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Docker Login
      - uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          
      - name: Build and push Docker images
        
        run: docker build -t williambpaiva/soma2devops:latest .
             echo "Deploying the project..."
