name: CI
on:
  push:
    branches:
      - main

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Docker Login
      - uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: |
            williambpaiva/soma2devops:v1
            williambpaiva/soma2devops:latest

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies      
        run: pip install Flask
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker Image
        run: docker build -t williambpaiva/soma2devops:latest .
             echo "Deploying the project..."

  alert-job:
    runs-on: windows-latest
    steps:
      - name: Send Telegram Alert
        env:
          TELEGRAM_TOKEN: '7082971552:AAGbOG6amP--nccNR9Oxpr4cdJylx-3f2zU'
          TELEGRAM_CHAT_ID: '-4245329360'
        shell: pwsh
        run: |
          $url = "https://api.telegram.org/bot${env:TELEGRAM_TOKEN}/sendMessage"
          $body = @{
            chat_id = "${env:TELEGRAM_CHAT_ID}"
            text = " -------NOTIFICACAO ENVIADA--------"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $url -Method Post -Body $body -ContentType "application/json"
